version: '3.8'

services:
  bigdata-sandbox:
    image: shiyamiii/bigdata-sandbox
    container_name: bigdata
    volumes:
      - ./logs:/var/bigdata/logs
      - hadoop_namenode:/var/bigdata/data/dfs/namenode
      - hadoop_datanode:/var/bigdata/data/dfs/datanode
      - kvstore_data:/var/bigdata/data/kvstore
    ports:
      - "2222:22"
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
      - "8042:8042"
      - "9000:9000"
      - "10000:10000"
      - "10002:10002"
      - "2181:2181"
      - "9092:9092"
      - "5000:5000"
      - "5001:5001"
      - "8888:8888"
    tty: true

volumes:
  hadoop_namenode:
  hadoop_datanode:
  kvstore_data: